### ISSUE TITLE
麻烦问下运行时一直没反应是问题出在哪

### ISSUE THREAD

**Issue by 17839792633** [Tjyy-1223/Neurosurgeon#3]

**Comment by Tjyy-1223** [comment]
先运行云端  python cloud_api.py -i 127.0.0.1 -p 9999 -d cpu
再运行边端 python edge_api.py -i 127.0.0.1 -p 9999 -d cpu -t alex_net
同时开启两个终端 上述两个命令都运行了吗？

**Comment by 17839792633** [comment]
> 
我在自己电脑模拟云端，把服务器ip端口号改成自己电脑的ip和端口号，然后在树莓派模拟边缘端运行，运行完云端之后运行边缘端就会输出：get bandwidth value : 0.5241484972934947 MB/s 非法指令然后停止了，云端就一直没反应了，不知道是哪出错了

**Comment by Tjyy-1223** [comment]
感觉是边缘端没有执行完毕，边端有没有报错信息，发来看一下。

云端没反应的原因是因为云端的主进程是会一直等待边缘端将中间数据传输过来才会执行，可能是因为你现在边缘端推理过程没有成功，中间数据也就没有产生并发送到云端，所以云端还在不断等待中。

**Comment by 17839792633** [comment]
> 感觉是边缘端没有执行完毕，边端有没有报错信息，发来看一下。
> 
> 云端没反应的原因是因为云端的主进程是会一直等待边缘端将中间数据传输过来才会执行，可能是因为你现在边缘端推理过程没有成功，中间数据也就没有产生并发送到云端，所以云端还在不断等待中。


边端没有报错，就是输出：get bandwidth value : 0.9218667976432569 MB/s
然后显示进程终止，云端也没有报错，就一直在运行

**Comment by 17839792633** [comment]
![image](https://github.com/Tjyy-1223/Neurosurgeon/assets/63998800/4e905b4d-56e2-4b08-a04a-f33d15669645)
边端运行的截图

**Comment by Tjyy-1223** [comment]
边缘端的执行流程如下：

- 获取带宽

- 在边缘端进行推理

目前的情况出现在边缘端没有正确执行完毕，我认为可能是和树莓派系统的兼容问题，可以做的排查有下面一些：

- 在edge_api.py的63、66以及70行输出一些信息，查看代码是否执行到这些位置

- 在net_utils.py中start_client做和1同样的操作，大概定位一下边端执行到哪个位置产生的非法指令

关于非法指令的报错我查到的都是系统兼容的问题，你可以参考一些进行一下排查：

1. [虚拟机 Python Illegal instruction 错误解决](https://azhuge233.com/%E8%99%9A%E6%8B%9F%E6%9C%BA-python-illegal-instruction-%E9%94%99%E8%AF%AF%E8%A7%A3%E5%86%B3/)
2. [NVIDIA JETSONTX2 安装 pytorch 出现错误：import torch 出现 Illegal instruction(core dumped)](https://blog.csdn.net/weixin_42899627/article/details/115000645)
3. [解决英伟达Jetson平台使用Python时的出现“Illegal instruction(cpre dumped)”错误](https://xiaosongshine.blog.csdn.net/article/details/114168235)
4. [Pytorch - Illegal instruction 解决](https://codeantenna.com/a/undcFppRjE)

其中最可能的原因是第4点提到的，pytorch安装与你的cpu不兼容，你可以找到对应的pytorch重新安装，或者迁移到gpu上运行试一试。

**Comment by 17839792633** [comment]
> 

麻烦问下您的运行设备和环境大概是什么样子

**Comment by 17839792633** [comment]
> 边缘端的执行流程如下：
> 
> * 获取带宽
> * 在边缘端进行推理
> 
> 目前的情况出现在边缘端没有正确执行完毕，我认为可能是和树莓派系统的兼容问题，可以做的排查有下面一些：
> 
> * 在edge_api.py的63、66以及70行输出一些信息，查看代码是否执行到这些位置
> * 在net_utils.py中start_client做和1同样的操作，大概定位一下边端执行到哪个位置产生的非法指令
> 
> 关于非法指令的报错我查到的都是系统兼容的问题，你可以参考一些进行一下排查：
> 
> 1. [虚拟机 Python Illegal instruction 错误解决](https://azhuge233.com/%E8%99%9A%E6%8B%9F%E6%9C%BA-python-illegal-instruction-%E9%94%99%E8%AF%AF%E8%A7%A3%E5%86%B3/)
> 2. [NVIDIA JETSONTX2 安装 pytorch 出现错误：import torch 出现 Illegal instruction(core dumped)](https://blog.csdn.net/weixin_42899627/article/details/115000645)
> 3. [解决英伟达Jetson平台使用Python时的出现“Illegal instruction(cpre dumped)”错误](https://xiaosongshine.blog.csdn.net/article/details/114168235)
> 4. [Pytorch - Illegal instruction 解决](https://codeantenna.com/a/undcFppRjE)
> 
> 其中最可能的原因是第4点提到的，pytorch安装与你的cpu不兼容，你可以找到对应的pytorch重新安装，或者迁移到gpu上运行试一试。

加输出指令后输出截图：
![image](https://github.com/Tjyy-1223/Neurosurgeon/assets/63998800/a4b377f6-4ed5-4f24-8987-881dbd844426)
![image](https://github.com/Tjyy-1223/Neurosurgeon/assets/63998800/b8b38a74-0189-4e58-8671-10ee8e595f00)

**Comment by Tjyy-1223** [comment]
我使用的设备是一个3080gpu主机和另一台只有cpu的笔记本。使用conda配置的虚拟环境在首页有写。

感觉你可以跑一些简单的pytorch代码和模型，测试一下你目前pytorch在树莓派上是否可以正确运行，测试一下是否是pytorch的版本问题。
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2023年7月7日(星期五)&nbsp;上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[Tjyy-1223/Neurosurgeon]&nbsp;麻烦问下运行时一直没反应是问题出在哪&nbsp;(Issue&nbsp;#3)



  
边缘端的执行流程如下：
  
获取带宽
 
在边缘端进行推理
  
目前的情况出现在边缘端没有正确执行完毕，我认为可能是和树莓派系统的兼容问题，可以做的排查有下面一些：
  
在edge_api.py的63、66以及70行输出一些信息，查看代码是否执行到这些位置
 
在net_utils.py中start_client做和1同样的操作，大概定位一下边端执行到哪个位置产生的非法指令
  
关于非法指令的报错我查到的都是系统兼容的问题，你可以参考一些进行一下排查：
  
虚拟机 Python Illegal instruction 错误解决
 
NVIDIA JETSONTX2 安装 pytorch 出现错误：import torch 出现 Illegal instruction(core dumped)
 
解决英伟达Jetson平台使用Python时的出现“Illegal instruction(cpre dumped)”错误
 
Pytorch - Illegal instruction 解决
  
其中最可能的原因是第4点提到的，pytorch安装与你的cpu不兼容，你可以找到对应的pytorch重新安装，或者迁移到gpu上运行试一试。
  
加输出指令后输出截图：
 
 
 
&mdash;

**Comment by 17839792633** [comment]
> 
树莓派我一直用来跑云边协同代码，之前跑的协同推理是没有问题的

**Comment by 17839792633** [comment]
> 我使用的设备是一个3080gpu主机和另一台只有cpu的笔记本。使用conda配置的虚拟环境在首页有写。 感觉你可以跑一些简单的pytorch代码和模型，测试一下你目前pytorch在树莓派上是否可以正确运行，测试一下是否是pytorch的版本问题。 ----&nbsp;原始邮件&nbsp;---- ***@***.***&gt;; Date:2023年7月7日(星期五)&nbsp;上午10:59 ***@***.***&gt;; ***@***.******@***.***&gt;; Subject:Re:&nbsp;[Tjyy-1223/Neurosurgeon]&nbsp;麻烦问下运行时一直没反应是问题出在哪&nbsp;(Issue&nbsp;#3) 边缘端的执行流程如下： 获取带宽 在边缘端进行推理 目前的情况出现在边缘端没有正确执行完毕，我认为可能是和树莓派系统的兼容问题，可以做的排查有下面一些： 在edge_api.py的63、66以及70行输出一些信息，查看代码是否执行到这些位置 在net_utils.py中start_client做和1同样的操作，大概定位一下边端执行到哪个位置产生的非法指令 关于非法指令的报错我查到的都是系统兼容的问题，你可以参考一些进行一下排查： 虚拟机 Python Illegal instruction 错误解决 NVIDIA JETSONTX2 安装 pytorch 出现错误：import torch 出现 Illegal instruction(core dumped) 解决英伟达Jetson平台使用Python时的出现“Illegal instruction(cpre dumped)”错误 Pytorch - Illegal instruction 解决 其中最可能的原因是第4点提到的，pytorch安装与你的cpu不兼容，你可以找到对应的pytorch重新安装，或者迁移到gpu上运行试一试。 加输出指令后输出截图： &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
